name: api_client
description: Api cleint for Demal app
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  connectivity_plus:
  dio:
  flutter:
    sdk: flutter
  meta:

dev_dependencies:
  mocktail:
  very_good_analysis: 
