include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_print: error
    empty_catches: ignore
    public_member_api_docs: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - require_trailing_commas
    - prefer_final_locals
    - always_declare_return_types
    - unnecessary_parenthesis
    - sort_child_properties_last