name: my_project
publish_to: none 

environment:
  sdk: ^3.9.0

workspace:
  - app
  - packages/core
  - packages/app_ui
  - packages/storage

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  melos: ^7.1.1 
  flutter_lints: ^5.0.0