name: bookings_repository
description: Bookings Repository package.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.1

dependencies:
  api_client:
  json_annotation:
  meta:


dev_dependencies:
  json_serializable:
  build_runner: 
  mocktail: 
  very_good_analysis:
  flutter_test:
    sdk: flutter 