name: client_tour_repository
description: "Demal APP Client Tour Repository."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  meta:
  json_annotation:
  core:


dev_dependencies:
  very_good_analysis:
  build_runner: 
  json_serializable:
