name: app
description: Demal APP UI package.
publish_to: "none"
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.10.1

flutter:
  uses-material-design: true

dependencies:
  # custom packages
  api_client:
  app_ui:
  auth_repository:
  bookings_repository:
  tour_repository:
  profile_repository:
  upload_repository:
  core:

  # dependencies
  bloc_concurrency:
  cached_network_image:
  carousel_slider:
  connectivity_plus:
  dio:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_map:
  go_router:
  image_picker:
  infinite_scroll_pagination:
  loader_overlay:
  mask_text_input_formatter:
  permission_handler:
  pinput:
  shimmer:
  smart_auth:
  storage:
  stream_transform:
  talker_bloc_logger:
  talker_flutter:
  talker_dio_logger:
  url_launcher:
  json_annotation:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  build_runner:
  json_serializable:
  mocktail:
  flutter_launcher_icons:
  flutter_native_splash:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../packages/app_ui/assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "../packages/app_ui/assets/images/logo.png"
  android_12:
    image: "../packages/app_ui/assets/images/logo.png"
    color: "#ffffff"
