name: app
description: Demal APP UI package.
publish_to: 'none' 
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
  app_ui:
  storage:
  auth_repository:
  client_tour_repository:

  
  flutter_bloc:
  intl:
  equatable: 
  loader_overlay:
  pinput:
  mask_text_input_formatter:
  go_router:
  get_it:
  talker_flutter:
  permission_handler:
  flutter_cache_manager:
  cached_network_image:
  image_picker:
  carousel_slider:
  flutter_map:
  latlong2:
  url_launcher:
  image_editor_plus:
  talker_bloc_logger: 
  smart_auth:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true 

