name: app
description: Demal APP UI package.
publish_to: 'none' 
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
  app_ui:
  storage:
  flutter_bloc:
  intl: ^0.20.2
  equatable: 
  loader_overlay: ^5.0.0
  pinput: ^5.0.2
  mask_text_input_formatter: ^2.9.0
  go_router:
  get_it:
  talker_flutter:
  permission_handler:
  flutter_cache_manager:
  cached_network_image:
  image_picker:
  carousel_slider:
  flutter_map:
  latlong2:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  uses-material-design: true
  generate: true
