name: core
description: "Demal APP Core."
resolution: workspace
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  app_ui:
  auth_repository:
  connectivity_plus:
  dio:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  meta:

  pinput:

  smart_auth:
  storage:
  talker_bloc_logger:
  talker_dio_logger:
  url_launcher:


dev_dependencies:
  very_good_analysis:
