name: core
description: "Demal APP Core."
resolution: workspace
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get_it:
  go_router:
  image_picker:
  url_launcher:
  dio:
  flutter_bloc:
  pretty_dio_logger:
  meta:
  connectivity_plus:

  talker_flutter: 
  talker_bloc_logger:
  talker_dio_logger:
  equatable: 
  smart_auth:
  pinput:
  
  storage:
  app_ui:
  auth_repository:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
