name: app_ui
description: Demal APP UI package.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  core: 
  storage:
  flutter_svg: 
  flutter_cache_manager:
  cached_network_image:
  shimmer: ^3.0.0
  go_router:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.10.0
  flutter_gen_runner:

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 120

  integrations:
    flutter_svg: true       