name: app_ui
description: Demal APP UI package.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  core: 
  storage:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
